"Welcome to Employee Program"

#CREATE DATABASE
CREATE DATABASE PAYROLL_SERVICE;
USE PAYROLL_SERVICE;

#CREATE TABLE
CREATE TABLE Employee_Payroll( create table employeePayroll(Id INT PRIMARY KEY AUTO INCREMENT,NAME VARCHAR(150) NOT NULL,SALARY DOUBLE NOT NULL,START DATE NOT NULL);

