"Welcome to Employee Program"

#CREATE DATABASE
CREATE DATABASE PAYROLL_SERVICE;
USE PAYROLL_SERVICE;

#CREATE TABLE
CREATE TABLE Employee_Payroll( create table employeePayroll(Id INT PRIMARY KEY AUTO INCREMENT,NAME VARCHAR(150) NOT NULL,SALARY DOUBLE NOT NULL,START DATE NOT NULL);

#Insert Records
INSERT INTO EMPLOYEEPAYROLL(ID,NAME,SALARY,START)
VALUES(1,'REKHA',20000,'2016-01-03'),
(2,'RIYA',300000,'2015-03-05'),
(3,'AARAV',25000,'2019-02-04'),
(4,'GANESH',40000,'2018-05-21');

#Retrieve Data
SELECT * FROM EMPLOYEEPAYROLL;

#Retrieve Salary
SELECT * FROM EMPLOYEEROLL
WHERE NAME='REKHA';

#ALTER TABLE
ALTER TABLE EMPLOYEEPAYROLL ADD GENDER VARCHAR(100) NOT NULL;

#UPDATE DATA
UPDATE EMPLOYEEPAYROLL SET GENDER='F'
WHERE NAME='REKHA' OR NAME='RIYA';

UPDATE EMPLOYEEPAYROLL SET GENDER='M'
WHERE NAME='AARAV' OR NAME='GANESH';

#FIND SUM,AVG,MIN,MAX, COUNT
SELECT SUM(SALARY) FROM EMPLOYEEPAYROLL WHERE GENDER='F' GROUP BY GENDER;
SELECT AVG(SALARY) FROM EMPLOYEEPAYROLL WHERE GENDER='M' GROUP BY GENDER;
SELECT MIN(SALARY) FROM EMPLOYEEPAYROLL WHERE GENDER='M' GROUP BY GENDER;
SELECT COUNT(SALARY) FROM EMPLOYEEPAYROLL WHERE GENDER='F' GROUP BY GENDER;
SELECT MAX,(SALARY) FROM EMPLOYEEPAYROLL WHERE GENDER='F' GROUP BY GENDER;

